=== kevinxshao/kevinxshao.github.io/ChangeEmailPage/changeemail.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://interdark.com/ChangeEmailPage/changeemail.xml" xmlns:tns="https://interdark.com/ChangeEmailPage/changeemail.xml" elementFormDefault="qualified">
 	
 	<xs:element name="WebPage">
 		<xs:complexType>
 			<xs:sequence>
 				<xs:element name="headPage" maxOccurs="1">
 					<xs:complexType>
 						<xs:sequence>
 							<xs:element name="titleText" type="xs:string" maxOccurs="1"/>
 						</xs:sequence>
 					</xs:complexType>
 				</xs:element>
 				<xs:element name="bodyPage" maxOccurs="1">
 					<xs:complexType>
 						<xs:sequence>
 							<xs:element name="topMenuBar" maxOccurs="1">
 								<xs:complexType>
 									<xs:sequence>
 										<xs:element name="firstMenuItem" maxOccurs="1">
 											<xs:complexType>
 												<xs:sequence>
 													<xs:element name="firstMenuItemName" type="xs:string" maxOccurs="1"/>
 													<xs:element name="firstdropitem" type="xs:string" maxOccurs="1"/>
 													<xs:element name="seconddropitem" type="xs:string" maxOccurs="1"/>
 													<xs:element name="thirddropitem" type="xs:string" maxOccurs="1"/>
 												</xs:sequence>
 											</xs:complexType>
 										</xs:element>
 										<xs:element name="secondMenuItem" type="xs:string" maxOccurs="1"/>
                                        <xs:element name="logoMenuItem" type="xs:string" maxOccurs="1"/>
 									</xs:sequence>
 								</xs:complexType>
 							</xs:element>
 							<xs:element name="emailChangeInterface" maxOccurs="1">
 								<xs:complexType>
 									<xs:sequence>
 										<xs:element name="emailChangeHeader" type="xs:string" maxOccurs="1"/>
 										<xs:element name="emailChangeParagraph" type="xs:string" maxOccurs="1"/>
 										<xs:element name="emailChangeCurrentPasswordText" type="xs:string" maxOccurs="1"/>
 										<xs:element name="emailChangeNewEmailText" type="xs:string" maxOccurs="1"/>
 										<xs:element name="emailChangeConfirmEmailText" type="xs:string" maxOccurs="1"/>
 										<xs:element name="emailChangeSubmitButton" type="xs:string" maxOccurs="1"/>
 									</xs:sequence>
 								</xs:complexType>
 							</xs:element>
 						</xs:sequence>
 					</xs:complexType>
 				</xs:element>
 			</xs:sequence>
 		</xs:complexType>
 	
 	</xs:element>


</xs:schema>

=== kevinxshao/kevinxshao.github.io/ChangeEmailPage/changeemail.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "changeemail.xsl"?>
<?xml-stylesheet href="changeemail.css"?>


<tns:WebPage xmlns:tns="https://interdark.com/ChangeEmailPage/changeemail.xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://interdark.com/ChangeEmailPage/changeemail.xml changeemail.xsd">
	<tns:headPage>
		<tns:titleText>InterDark | Change Email</tns:titleText>
	</tns:headPage>
	
	<tns:bodyPage>
		<tns:topMenuBar>
			<tns:firstMenuItem>
				<tns:firstMenuItemName>My Account</tns:firstMenuItemName>
				<tns:firstdropitem>Home</tns:firstdropitem>
				<tns:seconddropitem>Change Password</tns:seconddropitem>
				<tns:thirddropitem>Change Email</tns:thirddropitem>
			</tns:firstMenuItem>
	        <tns:secondMenuItem>Logout</tns:secondMenuItem>
            <tns:logoMenuItem>InterDark</tns:logoMenuItem>
		</tns:topMenuBar>
		
		<tns:emailChangeInterface>
			<tns:emailChangeHeader>Change your email?</tns:emailChangeHeader>
			<tns:emailChangeParagraph>Fill out the form below</tns:emailChangeParagraph>
			<tns:emailChangeCurrentPasswordText>Current Password:</tns:emailChangeCurrentPasswordText>
			<tns:emailChangeNewEmailText>New Email:</tns:emailChangeNewEmailText>
			<tns:emailChangeConfirmEmailText>Confirm New Email:</tns:emailChangeConfirmEmailText>
			<tns:emailChangeSubmitButton>Submit</tns:emailChangeSubmitButton>
		</tns:emailChangeInterface>
	</tns:bodyPage>
	
</tns:WebPage>
