=== kevinxshao/kevinxshao.github.io/NewsPage/news.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://interdark.com/NewsPage/news.xml" xmlns:tns="https://interdark.com/NewsPage/news.xml" elementFormDefault="qualified">
 	
 	<xs:element name="WebPage">
 		<xs:complexType>
 			<xs:sequence>
 				<xs:element name="headPage" maxOccurs="1">
 					<xs:complexType>
 						<xs:sequence>
 							<xs:element name="titleText" type="xs:string" maxOccurs="1"/>
 						</xs:sequence>
 					</xs:complexType>
 				</xs:element>
 				<xs:element name="bodyPage" maxOccurs="1">
 					<xs:complexType>
 						<xs:sequence>
 							<xs:element name="topMenuBar" maxOccurs="1">
 								<xs:complexType>
 									<xs:sequence>
 										<xs:element name="firstMenuItem" type="xs:string" maxOccurs="1"/>
 										<xs:element name="secondMenuItem" type="xs:string" maxOccurs="1"/>
 										<xs:element name="thirdMenuItem" type="xs:string" maxOccurs="1"/>
 										<xs:element name="fourthMenuItem" type="xs:string" maxOccurs="1"/>
 										<xs:element name="logoMenuItem" type="xs:string" maxOccurs="1"/>
 									</xs:sequence>
 								</xs:complexType>
 							</xs:element>
 							<xs:element name="newsInterface" maxOccurs="1">
 								<xs:complexType>
 									<xs:sequence>
 										<xs:element name="mainNews" maxOccurs="1">
 											<xs:complexType>
 												<xs:sequence>
 													<xs:element name="newsHeader" type="xs:string" maxOccurs="1"/>
 													<xs:element name="newsSubHeader" type="xs:string" maxOccurs="1"/>
 													<xs:element name="newsHeaderDescription" type="xs:string" maxOccurs="1"/>
 													<xs:element name="newsParagraph1" type="xs:string" maxOccurs="1"/>
 													<xs:element name="newsParagraph2" type="xs:string" maxOccurs="1"/> 													
 												</xs:sequence>
 											</xs:complexType>
 										</xs:element>
 										<xs:element name="aboutmeInterface" maxOccurs="1">
 											<xs:complexType>
 												<xs:sequence>
 													<xs:element name="aboutmeHeader" type="xs:string" maxOccurs="1"/>
 													<xs:element name="aboutmeParagraph" type="xs:string" maxOccurs="1"/> 		 		
 												</xs:sequence>
 											</xs:complexType>
 										</xs:element>
 										<xs:element name="myProjectsInterface" maxOccurs="1">
 											<xs:complexType>
 												<xs:sequence>
												 	<xs:element name="myProjectsHeader" type="xs:string" maxOccurs="1"/>
 													<xs:element name="myProjectsImage1text" type="xs:string" maxOccurs="1"/>
 													<xs:element name="myProjectsImage2text" type="xs:string" maxOccurs="1"/>
 													<xs:element name="myProjectsImage3text" type="xs:string" maxOccurs="1"/>
 												</xs:sequence>
 											</xs:complexType>
 										</xs:element>
 										<xs:element name="followmeInterface" maxOccurs="1">
 											<xs:complexType>
 												<xs:sequence>
												 	<xs:element name="followmeHeading" type="xs:string" maxOccurs="1"/>
 													<xs:element name="followmeparagraphtextp1" type="xs:string" maxOccurs="1"/>
 													<xs:element name="followmeparagraphtextp2" type="xs:string" maxOccurs="1"/>
 												</xs:sequence>
 											</xs:complexType>
 										</xs:element>
 									</xs:sequence>
 								</xs:complexType>
 							</xs:element>
							<xs:element name="pageInterface" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="pagenumbertext1" type="xs:string" maxOccurs="1"/>
										<xs:element name="pagenumbertext2" type="xs:string" maxOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
 						</xs:sequence>
 					</xs:complexType>
 				</xs:element>
 			</xs:sequence>
 		</xs:complexType>
 	
 	</xs:element>


</xs:schema>

=== kevinxshao/kevinxshao.github.io/NewsPage/news.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "news.xsl"?>
<?xml-stylesheet href="news.css"?>

<tns:WebPage xmlns:tns="https://interdark.com/NewsPage/news.xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://interdark.com/NewsPage/news.xml news.xsd">
	<tns:headPage>
		<tns:titleText>InterDark | News</tns:titleText>
	</tns:headPage>
	
	<tns:bodyPage>
		<tns:topMenuBar>
			<tns:firstMenuItem>Login</tns:firstMenuItem>
	        <tns:secondMenuItem>News</tns:secondMenuItem>
	        <tns:thirdMenuItem>Contact</tns:thirdMenuItem>
	        <tns:fourthMenuItem>About</tns:fourthMenuItem>
	        <tns:logoMenuItem>InterDark</tns:logoMenuItem>
		</tns:topMenuBar>
		<tns:newsInterface>
			<tns:mainNews>
				<tns:newsHeader>InterDark News</tns:newsHeader>
				<tns:newsSubHeader>Breaking News</tns:newsSubHeader>
				<tns:newsHeaderDescription>InterDark Formation, May 29, 2021</tns:newsHeaderDescription>
				<tns:newsParagraph1>I am currently in the process of creating the InterDark website. So far we have completed the login feature, account creation feature, and reset password feature.</tns:newsParagraph1>
				<tns:newsParagraph2>The next step to this website will be finishing the news blog, contact page and the meet the team page.</tns:newsParagraph2>
			</tns:mainNews>
			<tns:aboutmeInterface>
				<tns:aboutmeHeader>About Me</tns:aboutmeHeader>
				<tns:aboutmeParagraph>Hi my name is Kevin and I am a Computer Engineer. I have a focus in Software Engineering but I also work on other fields such as Embedded Systems, Web Development and Android App Development. In my spare time I like to watch tv shows and play games. I am currently watching The Flash and Bad Batch. The game I currently play is osu.</tns:aboutmeParagraph>
			</tns:aboutmeInterface>
			<tns:myProjectsInterface>
                <tns:myProjectsHeader>My Projects</tns:myProjectsHeader>
				<tns:myProjectsImage1text>Embedded Systems</tns:myProjectsImage1text>
				<tns:myProjectsImage2text>App Development</tns:myProjectsImage2text>
				<tns:myProjectsImage3text>Programming</tns:myProjectsImage3text>
			</tns:myProjectsInterface>
			<tns:followmeInterface>
                <tns:followmeHeading>Follow Me</tns:followmeHeading>
				<tns:followmeparagraphtextp1>GitHub: </tns:followmeparagraphtextp1>
				<tns:followmeparagraphtextp2>https://github.com/kevinxshao</tns:followmeparagraphtextp2>
			</tns:followmeInterface>
		</tns:newsInterface>
        <tns:pageInterface>
            <tns:pagenumbertext1>Page 1 / 1 </tns:pagenumbertext1>
            <tns:pagenumbertext2>Next Page</tns:pagenumbertext2>
        </tns:pageInterface>
	</tns:bodyPage>
	
</tns:WebPage>
