=== kevinxshao/kevinxshao.github.io/AboutPage/about.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://interdark.com/AboutPage/about.xml" xmlns:tns="https://interdark.com/AboutPage/about.xml" elementFormDefault="qualified">
 	
 	<xs:element name="WebPage">
 		<xs:complexType>
 			<xs:sequence>
 				<xs:element name="headPage" maxOccurs="1">
 					<xs:complexType>
 						<xs:sequence>
 							<xs:element name="titleText" type="xs:string" maxOccurs="1"/>
 						</xs:sequence>
 					</xs:complexType>
 				</xs:element>
 				<xs:element name="bodyPage" maxOccurs="1">
 					<xs:complexType>
 						<xs:sequence>
 							<xs:element name="topMenuBar" maxOccurs="1">
 								<xs:complexType>
 									<xs:sequence>
 										<xs:element name="firstMenuItem" type="xs:string" maxOccurs="1"/>
 										<xs:element name="secondMenuItem" type="xs:string" maxOccurs="1"/>
 										<xs:element name="thirdMenuItem" type="xs:string" maxOccurs="1"/>
 										<xs:element name="fourthMenuItem" type="xs:string" maxOccurs="1"/>
 										<xs:element name="logoMenuItem" type="xs:string" maxOccurs="1"/>
 									</xs:sequence>
 								</xs:complexType>
 							</xs:element>
 							<xs:element name="meettheteamInterface" maxOccurs="1">
 								<xs:complexType>
 									<xs:sequence>
 										<xs:element name="meettheteamheader" type="xs:string" maxOccurs="1"/>
 										<xs:element name="meettheteamParagraph" type="xs:string" maxOccurs="1"/>
 										<xs:element name="member1" maxOccurs="1">
 											<xs:complexType>
 												<xs:sequence>
 													<xs:element name="member1Name" type="xs:string" maxOccurs="1"/>
 													<xs:element name="member1Job" type="xs:string" maxOccurs="1"/>
 													<xs:element name="member1Paragraph1" type="xs:string" maxOccurs="1"/>
 													<xs:element name="member1Contact" type="xs:string" maxOccurs="1"/>
 												</xs:sequence>
 											</xs:complexType>
 										</xs:element>
 										<xs:element name="member2" maxOccurs="1">
 											<xs:complexType>
 												<xs:sequence>
 													<xs:element name="member2Name" type="xs:string" maxOccurs="1"/>
 													<xs:element name="member2Job" type="xs:string" maxOccurs="1"/>
 													<xs:element name="member2Paragraph2" type="xs:string" maxOccurs="1"/>
 													<xs:element name="member2Contact" type="xs:string" maxOccurs="1"/>
 												</xs:sequence>
 											</xs:complexType>
 										</xs:element>
 										<xs:element name="member3" maxOccurs="1">
 											<xs:complexType>
 												<xs:sequence>
 													<xs:element name="member3Name" type="xs:string" maxOccurs="1"/>
 													<xs:element name="member3Job" type="xs:string" maxOccurs="1"/>
 													<xs:element name="member3Paragraph3" type="xs:string" maxOccurs="1"/>
 													<xs:element name="member3Contact" type="xs:string" maxOccurs="1"/>
 												</xs:sequence>
 											</xs:complexType>
 										</xs:element>
 										<xs:element name="member4" maxOccurs="1">
 											<xs:complexType>
 												<xs:sequence>
 													<xs:element name="member4Name" type="xs:string" maxOccurs="1"/>
 													<xs:element name="member4Job" type="xs:string" maxOccurs="1"/>
 													<xs:element name="member4Paragraph4" type="xs:string" maxOccurs="1"/>
 													<xs:element name="member4Contact" type="xs:string" maxOccurs="1"/>
 												</xs:sequence>
 											</xs:complexType>
 										</xs:element>
 									</xs:sequence>
 								</xs:complexType>
 							</xs:element>
 						</xs:sequence>
 					</xs:complexType>
 				</xs:element>
 			</xs:sequence>
 		</xs:complexType>
 	
 	</xs:element>


</xs:schema>

=== kevinxshao/kevinxshao.github.io/AboutPage/about.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "about.xsl"?>
<?xml-stylesheet href="about.css"?>

<tns:WebPage xmlns:tns="https://interdark.com/AboutPage/about.xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://interdark.com/AboutPage/about.xml about.xsd">
	<tns:headPage>
		<tns:titleText>InterDark | About</tns:titleText>
	</tns:headPage>
	
	<tns:bodyPage>
		<tns:topMenuBar>
			<tns:firstMenuItem>Login</tns:firstMenuItem>
	        <tns:secondMenuItem>News</tns:secondMenuItem>
	        <tns:thirdMenuItem>Contact</tns:thirdMenuItem>
	        <tns:fourthMenuItem>About</tns:fourthMenuItem>
	        <tns:logoMenuItem>InterDark</tns:logoMenuItem>
		</tns:topMenuBar>
		
		<tns:meettheteamInterface>
			<tns:meettheteamheader>Meet The Team</tns:meettheteamheader>
			<tns:meettheteamParagraph>Below is all the members of the team along with a small description of each member.</tns:meettheteamParagraph>
			<tns:member1>
				<tns:member1Name>Kevin Shao</tns:member1Name>	
				<tns:member1Job>CEO &amp; Founder</tns:member1Job>
				<tns:member1Paragraph1>Hello I'm a Computer Engineer with a focus in Software Development. My hobbies include playing games, watching tv shows and developing Android Apps</tns:member1Paragraph1>
				<tns:member1Contact>Contact</tns:member1Contact>
			</tns:member1>
			
			<tns:member2>
				<tns:member2Name>Me</tns:member2Name>	
				<tns:member2Job>Computer Engineer</tns:member2Job>
				<tns:member2Paragraph2>I enjoy Web Develpment. I have worked with HTML, CSS, JavaScript, XML, XSLT, XSD, and Xpath. Some hobbies I enjoy is I like to workout mainly doing calisthenics.</tns:member2Paragraph2>
				<tns:member2Contact>Contact</tns:member2Contact>
			</tns:member2>
			
			<tns:member3>
				<tns:member3Name>Myself</tns:member3Name>	
				<tns:member3Job>Programmer</tns:member3Job>
				<tns:member3Paragraph3>I enjoy Android App Develpment. I have created a simple math testing game called Math Shapers. It is currently in its pre alpha phase and only tests addition, subtraction and multiplication.</tns:member3Paragraph3>
				<tns:member3Contact>Contact</tns:member3Contact>
			</tns:member3>			
			
			<tns:member4>
				<tns:member4Name>I</tns:member4Name>	
				<tns:member4Job>Embedded Systems</tns:member4Job>
				<tns:member4Paragraph4>I enjoy working with Arduino. I used Arduino to develop a drop system for a concert. It was used to drop tickets from the ceiling.</tns:member4Paragraph4>
				<tns:member4Contact>Contact</tns:member4Contact>
			</tns:member4>				
		</tns:meettheteamInterface>
	</tns:bodyPage>
	
</tns:WebPage>
