=== kevinxshao/kevinxshao.github.io/ContactPage/contact.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://interdark.com/ContactPage/contact.xml" xmlns:tns="https://interdark.com/ContactPage/contact.xml" elementFormDefault="qualified">
 	
 	<xs:element name="WebPage">
 		<xs:complexType>
 			<xs:sequence>
 				<xs:element name="headPage" maxOccurs="1">
 					<xs:complexType>
 						<xs:sequence>
 							<xs:element name="titleText" type="xs:string" maxOccurs="1"/>
 						</xs:sequence>
 					</xs:complexType>
 				</xs:element>
 				<xs:element name="bodyPage" maxOccurs="1">
 					<xs:complexType>
 						<xs:sequence>
 							<xs:element name="topMenuBar" maxOccurs="1">
 								<xs:complexType>
 									<xs:sequence>
 										<xs:element name="firstMenuItem" type="xs:string" maxOccurs="1"/>
 										<xs:element name="secondMenuItem" type="xs:string" maxOccurs="1"/>
 										<xs:element name="thirdMenuItem" type="xs:string" maxOccurs="1"/>
 										<xs:element name="fourthMenuItem" type="xs:string" maxOccurs="1"/>
 										<xs:element name="logoMenuItem" type="xs:string" maxOccurs="1"/>
 									</xs:sequence>
 								</xs:complexType>
 							</xs:element>
 							<xs:element name="discordlinkInterface" maxOccurs="1">
 								<xs:complexType>
 									<xs:sequence>
 										<xs:element name="discordlinkHeader" type="xs:string" maxOccurs="1"/>
										<xs:element name="discordlinkParagraph" type="xs:string" maxOccurs="1"/>
 									</xs:sequence>
 								</xs:complexType>
 							</xs:element>
 						</xs:sequence>
 					</xs:complexType>
 				</xs:element>
 			</xs:sequence>
 		</xs:complexType>
 	
 	</xs:element>


</xs:schema>

=== kevinxshao/kevinxshao.github.io/ContactPage/contact.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type = "text/xsl" href = "contact.xsl"?>
<?xml-stylesheet href="contact.css"?>

<tns:WebPage xmlns:tns="https://interdark.com/ContactPage/contact.xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://interdark.com/ContactPage/contact.xml contact.xsd">
	<tns:headPage>
		<tns:titleText>InterDark | About</tns:titleText>
	</tns:headPage>
	
	<tns:bodyPage>
		<tns:topMenuBar>
			<tns:firstMenuItem>Login</tns:firstMenuItem>
	        <tns:secondMenuItem>News</tns:secondMenuItem>
	        <tns:thirdMenuItem>Contact</tns:thirdMenuItem>
	        <tns:fourthMenuItem>About</tns:fourthMenuItem>
	        <tns:logoMenuItem>InterDark</tns:logoMenuItem>
		</tns:topMenuBar>
		
		<tns:discordlinkInterface>
			<tns:discordlinkHeader>Need to contact us?</tns:discordlinkHeader>
            <tns:discordlinkParagraph>Come join our Discord</tns:discordlinkParagraph>
		</tns:discordlinkInterface>
	</tns:bodyPage>
	
</tns:WebPage>
